### ISSUE TITLE
Add FixPCIeLinkRate.efi to OCLP

### ISSUE THREAD

**Issue by joevt** [joevt/joevtApps#1]
For https://github.com/dortania/OpenCore-Legacy-Patcher/issues/406

Replies are unnecessarily blocked in the OCLP github so I've added this issue here.

**Comment by moosethegoose2213** [comment]
Hi!
The GitHub issues are not "unnecessarily blocked." I'd highly recommend you to read [this](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/985) issue, as it explains in great detail why he's disabled them. Mykola is the sole maintainer of the issues page, and he felt that it'd be better for both his and his family's well-being to be able to spare as much time for them as possible. 

I truly would hope that if something similar happened to your relatives and fellow countrymen, you'd care about them enough to "unnecessarily block" issues to spend more time with them. I know I would.

\- ASentientHedgehog

**Comment by joevt** [comment]
[That](https://github.com/dortania/OpenCore-Legacy-Patcher/issues/985) issue says "closing new issues" but it's also disabling comments on existing issues which stops other people who do have time from helping with or updating those issues. If he doesn't have time for new issues then he can just ignore them and let other people deal with it.

**Comment by khronokernel** [comment]
> If he doesn't have time for new issues then he can just ignore them and let other people deal with it.

People were abusing the existing issues and filing their own issues within them, I cannot just "ignore" them when they're being flooded with garbage and I'm the only person willing to even manage issues at that time. There's a reason the Discord server was setup, it's to migrate issues there and let community members help out. You could've reached out there and notified other developers. I'm sorry this wasn't to your liking.

Regardless, it's integrated. You can close this issue:
* https://github.com/dortania/OpenCore-Legacy-Patcher/commit/f4cb0bed68ca73b624a9f334bce84a4d9e9318af
